<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8U4S44M" failures="0" tests="4" name="com.pygacrm.opportunity.CreateOpportunityTest" time="41.619" errors="1" timestamp="2023-07-11T10:46:48 IST" skipped="3">
  <testcase classname="com.pygacrm.opportunity.CreateOpportunityTest" name="CreateOpportunityWithName" time="9.833">
    <error message="Cannot invoke &quot;java.lang.CharSequence.toString()&quot; because &quot;s&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "s" is null
at java.base/java.lang.String.contains(String.java:2852)
at com.Pyga.Vtigergenericutlity.WebActionUtility.swithToWindowBasedOnURL(WebActionUtility.java:143)
at com.pygacrm.opportunity.CreateOpportunityTest.CreateOpportunityWithName(CreateOpportunityTest.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- CreateOpportunityWithName -->
  <testcase classname="com.pygacrm.opportunity.CreateOpportunityTest" name="CreateOpportunityWithName" time="12.434">
    <skipped/>
  </testcase> <!-- CreateOpportunityWithName -->
  <testcase classname="com.pygacrm.opportunity.CreateOpportunityTest" name="CreateOpportunityWithName" time="9.435">
    <skipped/>
  </testcase> <!-- CreateOpportunityWithName -->
  <testcase classname="com.pygacrm.opportunity.CreateOpportunityTest" name="CreateOpportunityWithName" time="9.917">
    <skipped/>
  </testcase> <!-- CreateOpportunityWithName -->
  <system-out>
    <![CDATA[DataBase is Connected 
BeforeTest
BROWSER IS LAUNCHED 
Successfully Logged to Application
Log Out from Application
Successfully Logged to Application
Log Out from Application
Successfully Logged to Application
Log Out from Application
Successfully Logged to Application
Log Out from Application
Browser is Closed 
AfterTest
DataBase connection  is Closed ]]>
  </system-out>
</testsuite> <!-- com.pygacrm.opportunity.CreateOpportunityTest -->
